services:
  - type: web
    name: food-ai-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.9
      - key: GOOGLE_API_KEY
        sync: false  # You'll need to add this in Render dashboard